### ISSUE TITLE
[0.0.2] TODO

### ISSUE THREAD

**Issue by jtara1** [jtara1/InhaleGreenSubsistence#6]
Todo for myself:

- [x] info graphics in lvl1 for teaching controls
- [x] make babies more apparent (wee sound & vfx of skinny ring growing out)
- [x] boxes that break on collision
- [ ] draw indicator when char can grapple to wall or ceiling
- [x] respawn and preserve size
- [x] make saws move
