### ISSUE TITLE
[0.0.4] TODO

### ISSUE THREAD

**Issue by jtara1** [jtara1/InhaleGreenSubsistence#7]
this is the 2nd to last release I plan on doing

1.0.0 should just include bug fixes and finishing touches

for myself:

ui:
- [x] main menu ui
- [ ] pause game ui & feature
- [x] overworld hub / level selector
- [x] finish game ui
- [ ] lvl victory and transition to hub or next lvl
- [ ] finish parallex bg and make it look not bad

gameplay:
- [x] make dash a limited use skill & item
- [ ] add coins for player to gain & score & lvl timer
- [ ] track score & time per level
- [ ] serialize score per lvl?
- [ ] add variants of box and make them `move_and_slide`

juice:
- [x] add songs
