### ISSUE TITLE
[1.0.0] TODO

### ISSUE THREAD

**Issue by jtara1** [jtara1/InhaleGreenSubsistence#9]
As we approach the hard deadline for the game jam, I'll focus on making the game a complete game and pulling together all the pieces and providing a good UX.

todo for myself:

must have:
- [x] make each level winnable (ie add space ship to reach and fly away in)
- [ ] pause menu: resume, exit to main menu

nice to have:
- [x] variants of boxes to enable more level design
- [x] mask sprite img so we dont have 2 lines of pixels of annoying green at top
- [x] nicer parallex bg
- [ ] transitions between `load_scene` calls so it's not a hard cut
- [x] sfx for char actions and make pitch scale with size

could include:
- [ ] music player manager global

**Comment by jtara1** [comment]
I didn't do the pitch scaling with size but it would've been a really nice touch.
I ended up not needing to mask sprite bc apparently I just had to re-import the spritesheet with `mipmaps = true`

Josh finished up Lv3 and did some of my assignments.
